input:
  file:
    paths: [ ./rpk/connect/data/* ]
    codec: lines

pipeline:
  processors:
    - sleep:
        duration: "1000ms"

    - log:
        level: INFO
        message: "Publishing message"
        fields_mapping: root.id = this.id

output:
  kafka:
    addresses:
      - "localhost:9092"
    topic: payments
    target_version: 2.0.0

logger:
  format: logfmt